### ISSUE TITLE
Instalation Instructions

### ISSUE THREAD

**Issue by MattCarneiro** [yurikuzn/espo-funnel-chart#13]
Hello my frieend

how to install your package?

**Comment by yurikuzn** [comment]
Hi,

It was developed for EspoCRM without consideration that is will be needed elsewhere.

We just install it from GitHub https://github.com/espocrm/espocrm/blob/8.4.2/package.json#L55.

**Comment by MattCarneiro** [comment]
> Hi,
> 
> It was developed for EspoCRM without consideration that is will be needed elsewhere.
> 
> We just install it from GitHub https://github.com/espocrm/espocrm/blob/8.4.2/package.json#L55.

I have EspoCRM installed on my server. However, I don't know how can I get this funnel view. May you give instructions?

I think this view would be much better in hand if we could apply to entities, such as what happens to Kanban View.
So I can create an entity and make the registers as Funnel View and set the order of the funnel. So, leads show on the level of funnel they are. Funnel view stages could be picked from list view as what happens with kanban view

**Comment by yurikuzn** [comment]
It's a standard dashlet. Can be added from the dashboard for by a user who have access to Opportunities.
